site_name: Статический сайт на MkDocs
site_url: https://krllkrnv.github.io/mkdocs-test
site_description: Демонстрация развертывания статического сайта

theme:
  name: material
  palette:
    - scheme: default
      primary: blue
      accent: light blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

nav:
  - Главная: index.md

plugins:
  - search
  - social

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/krllkrnv
